[project]
name = "ScoreAI"
version = "0.1.0"
description = "scoreai monorepo"
dependencies = [
    "beautifulsoup4>=4.14.3",
]

[tool.uv.workspace]
members = ["backend", "frontend", "shared"]

[tool.mypy]
mypy_path = "shared:backend:frontend"
explicit_package_bases = true
