name: Docker Test Suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create empty .env file
        run: |
          touch .env
      - name: Build and Start Containers
        run: |
          # We use the -d flag to run in the background
          docker compose up -d --build

      - name: Wait for services to be ready
        # Databases often take a few seconds to initialize
        run: sleep 10 

      - name: Run Backend Tests
        # Run your pytest suite inside the running container
        run: docker compose exec -T backend pytest backend

      - name: Run Frontend Tests
        # Run your pytest suite inside the running container
        run: docker compose exec -T frontend pytest frontend

      - name: Check Container Logs (If failed)
        if: failure()
        run: docker compose logs

      - name: Stop Containers
        if: always()
        run: docker compose down
